feat: add version check + other minor fixes

diff --git a/wg-vpn b/wg-vpn
--- a/wg-vpn
+++ b/wg-vpn
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+if ((BASH_VERSION[0] < 4 || (BASH_VERSION[0] == 4 && BASH_VERSION[1] < 3))); then
+    echo "Error: This script requires Bash 4.3 or higher." >&2
+    exit 1
+fi
+
 SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
 
 # XDG base dir paths
@@ -21,6 +26,7 @@ DEPENDENCIES=(
     "ufw"
     "sudo"
     "ip"
+    "flock"
 )
 ENTRYPOINT_LOADED="true"
 
